
<form name="form_value" method="POST" id="form_value">
    <label>Lowest Price</label><br/>
    <input type="text" id="lowprice" name="lowprice" class="form-control input-md" data-validate="{'validate-zero-or-greater':true, required: true}" style="margin:20px;width:300px;" autocomplete="off"><br/>
    <label>Highest Price</label><br/>
    <input type="text" id="highprice" name="highprice" class="form-control input-md" style="margin:20px;width:300px;" autocomplete="off" data-validate="{'validate-zero-or-greater':true, 'validate-range':true, required:true}"><br/>
    <label>Sort by Price</label><br/>
    <select name="sortorder" id="sortorder" class="form-control input-md" style="margin:20px;width:300px;" autocomplete="off" data-validate="{'validate-select':true, required:true}">
        <option name="ascending" value="ASC">Ascending</option>
        <option name="descending" value="DESC">Descending</option>
    </select>
    <br/>
    <br>

    <button type="button" id="queryProducts"  name="query-products-submit" value="Query Products">Query Results</button>
</form>
<br/>
<br/>
<div class="result" style="display:none"></div>

<script type="text/x-magento-init">
{
    "#form_value": {
        "validation": {}
    }
}
</script>
<script>
require(['jquery','mage/mage'],function(){
    jQuery(document).ready(function() {
        jQuery(".result").hide();
        var lowPriceEl = jQuery("#lowprice");
        var highPriceEl = jQuery("#highprice");
        jQuery(lowPriceEl).on("change", function(){
            var lowPriceVal = jQuery(lowPriceEl).val();
            if (lowPriceVal === "0") {
                // add 5 to it to make high price limit
                var highPriceLimit = 5;
                // remove previous range string class
                jQuery(highPriceEl).removeClass();
                // build class range string 
                var rangeString = "range-"+lowPriceVal+"-"+highPriceLimit;
                // add class attribute with new string to highPrice input element
                jQuery(highPriceEl).addClass([rangeString,"form-control", "input-md"]);

            }
            else if (lowPriceVal > 0) {
                var highPriceLimit = lowPriceVal * 5;
                // remove previous range string class
                jQuery(highPriceEl).removeClass();
                // build class range string
                var rangeString = "range-"+lowPriceVal+"-"+highPriceLimit;
                // add class attribute to highPrice input element
                jQuery(highPriceEl).addClass([rangeString,"form-control", "input-md"]);
            }
        });
        jQuery("#queryProducts").on('click', function(){
        //jQuery("#form_value").mage('validation');
        if (jQuery('#form_value').validation('isValid')) {
            var lowPrice = jQuery("input[name='lowprice']").val();
            var highPrice = jQuery("input[name='highprice']").val();
            var sortOrder = jQuery("#sortorder").children("option:selected").val();

            var url = "<?php echo $block->getBaseUrl().'custaccounttab/result/result/' ?>";
            jQuery.ajax({
            url: url,
            type: "POST",
            data: {lowprice:lowPrice,highprice:highPrice,sortorder:sortOrder},
            showLoader: true,
            cache: false,
            success: function(response){
                jQuery(".result").show();
                jQuery(".result").html(response.output);
            }
            });
        }        
        });
    });
});
</script>
