
<form name="form_value" method="POST" id="form_value" data-mage-init='{"validation": {}}'>
    <label>Lowest Price</label><br/>
    <input type="text" name="lowprice" class="form-control input-md" data-validate="{'validate-zero-or-greater':true}" style="margin:20px;width:300px;" autocomplete="off"><br/>
    <label>Highest Price</label><br/>
    <input type="text" name="highprice" class="form-control input-md" style="margin:20px;width:300px;" autocomplete="off" data-validate="{'validate-zero-or-greater':true}"><br/>
    <label>Sort by Price</label><br/>
    <select name="sortorder" id="sortorder" class="form-control input-md" style="margin:20px;width:300px;" autocomplete="off" data-validate="{'validate-select':true}">
        <option name="ascending" value="ascending">Ascending</option>
        <option name="descending" value="descending">Descending</option>
    </select>
    <br/>

    <input type="submit" id="queryProducts"  name="query-products-submit" value="Query Products">
</form>
<br/>
<br/>
Result<div class="result" style="display:none">
    <h1 style="text-align:center;">If this is showing that means the jQuery script worked</h1>
</div>


<script>
require(['jquery','mage/mage'],function(){
    jQuery(document).ready(function() {
        jQuery(".result").hide();
        jQuery("#form_value").mage('validation', {});
        jQuery("#form_value").submit(function(){
            
            var lowPrice = jQuery("input[name='lowprice']").val();
            var highPrice = jQuery("input[name='highprice']").val();
            var sortOrder = jQuery("#sortorder").children("option:selected").val();

            var url = "<?php echo $block->getBaseUrl().'custaccounttab/result/result/' ?>";
            jQuery.ajax({
            url: url,
            type: "POST",
            data: {lowprice:lowPrice,highprice:highPrice,sortorder:sortOrder},
            showLoader: true,
            cache: false,
            success: function(response){
                console.log(response.output);
                jQuery(".result").show();
                jQuery(".result").html(response.output);
            }
        });
        return false;
        });
    });
});
</script>
<script type="text/x-magento-init">
{
    "#form_value": {
        "validation": {}
    }
}
</script>